tproxy-port: 7893
bind-address: '*'
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: true
secret : ""
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  nameserver:
    - https://cloudflare-dns.com/dns-query
  fallback:
    - https://dns.google/dns-query  
proxies:
  - {name: "[Trojan] SG-OVH", server: sg4-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 06652d20-5ae8-11ec-8d34-1239d0255272, sni: maps.google.com, skip-cert-verify: true}
  - {name: "[Trojan] SG-HE 2", server: sg2-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 17ce6840-5ae8-11ec-9cda-1239d0255272, sni: maps.google.com, skip-cert-verify: true}
  - {name: "[Trojan] SG-HE 3", server: sg3-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 2a5fb160-5ae8-11ec-bb6e-1239d0255272, sni: maps.google.com, skip-cert-verify: true}
  - {name: "[Trojan] SG-HE MUX", server: sg6-trojan.bonds.id, port: 443, udp: true, type: trojan, password: 350cf240-5ae8-11ec-8ec8-1239d0255272, sni: maps.google.com, skip-cert-verify: true}

proxy-groups:
  - name: AKUN
    type: select
    proxies: 
      - "[Trojan] SG-OVH"
      - "[Trojan] SG-HE 2"
      - "[Trojan] SG-HE 3"
      - "[Trojan] SG-HE MUX"
rules:
  - MATCH,AKUN
